image: maven:3-jdk-8

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

stages:
    - lint
    - build_deploy

lint:
    stage: lint
    script:
        - mvn checkstyle:check

build_deploy:
    stage: build_deploy
    only: 
        - master
        - develop
    script:
        - bash deploy.sh